# Generated by Django 5.0.7 on 2024-08-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_standard', models.CharField(max_length=255, verbose_name='Название стандарт пакета')),
                ('price_standard', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена стандарт')),
                ('document_package_standard', models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ пакета')),
                ('document_medicine_standard', models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ медикаментов')),
                ('name_comfort', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название комфорт пакета')),
                ('price_comfort', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена комфорт')),
                ('document_package_comfort', models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ пакета')),
                ('document_massage_comfort', models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ медикаментов')),
                ('name_vip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название VIP пакета')),
                ('price_vip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена VIP')),
                ('document_package_vip', models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ пакета')),
                ('document_massage_vip', models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ медикаментов')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('price_comfort', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена комфорт')),
                ('available_in_comfort', models.BooleanField(default=False, null=True, verbose_name='Доступна в комфорте')),
                ('price_vip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена vip')),
                ('available_in_vip', models.BooleanField(default=True, null=True, verbose_name='Доступна в vip')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
