# Generated by Django 5.0.7 on 2024-08-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_packages_packageservice_remove_service_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageservice',
            options={'verbose_name': 'Услуга пакета', 'verbose_name_plural': 'Услуги пакета'},
        ),
    ]
