# Generated by Django 5.0.7 on 2024-08-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_alter_packageservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория цен', 'verbose_name_plural': 'Категории цен'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
    ]
