# Generated by Django 5.0.7 on 2024-08-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_alter_category_options_alter_service_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='document_massage_comfort',
            new_name='document_medicine_comfort',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='document_massage_vip',
            new_name='document_medicine_vip',
        ),
    ]
