# Generated by Django 5.0.7 on 2024-08-23 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_rename_document_massage_comfort_packages_document_medicine_comfort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='packageservice',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prices.packageservicetype', verbose_name='Тип'),
        ),
    ]
