# Generated by Django 5.0.7 on 2024-08-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_packageservicetype_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageservice',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='prices.packageservicetype', verbose_name='Тип'),
        ),
    ]
