# Generated by Django 5.0.7 on 2024-08-23 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_alter_packageservice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageservicetype',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='prices.packages', verbose_name='Пакет'),
        ),
    ]
