# Generated by Django 5.0.7 on 2024-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_alter_packageservicetype_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tooltip',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Подсказка'),
        ),
    ]
