# Generated by Django 5.0.7 on 2024-08-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0010_service_tooltip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageservicetype',
            options={'verbose_name': 'Тип сервиса в пакете', 'verbose_name_plural': 'Типы сервисов в пакете'},
        ),
    ]
