# Generated by Django 5.0.7 on 2024-08-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0011_alter_packageservicetype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='all_prices',
            field=models.FileField(blank=True, null=True, upload_to='prices', verbose_name='Все цены'),
        ),
    ]
