# Generated by Django 5.0.7 on 2024-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0013_packages_comfort_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='acheges_for_pregnancy',
            field=models.FileField(blank=True, null=True, upload_to='prices', verbose_name='Документы для беременности'),
        ),
        migrations.AddField(
            model_name='packages',
            name='all_packeges',
            field=models.FileField(blank=True, null=True, upload_to='prices', verbose_name='Все Пакеты'),
        ),
    ]
