# Generated by Django 5.0.7 on 2024-08-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='categories', verbose_name='Иконка'),
        ),
    ]
