# Generated by Django 5.0.7 on 2024-08-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
