# Generated by Django 5.0.7 on 2024-09-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services', verbose_name='Изображение'),
        ),
    ]
