# Generated by Django 5.0.7 on 2024-11-04 10:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_category_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['order'], 'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AddField(
            model_name='type',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
