# Generated by Django 5.0.7 on 2024-08-21 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcard',
            name='image',
            field=models.FileField(upload_to='about', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='aboutfaqimage',
            name='image',
            field=models.FileField(upload_to='about', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='aboutgallery',
            name='image',
            field=models.FileField(upload_to='about/gallery', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.FileField(upload_to='about', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='aboutpartners',
            name='image',
            field=models.FileField(upload_to='about/partners', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='welcomepage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='welcome', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='about-images', verbose_name='Изображение')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.aboutpage', verbose_name='Страница')),
            ],
        ),
    ]
