# Generated by Django 5.0.7 on 2024-08-22 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_aboutcard_image_alter_aboutfaqimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutimages',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.aboutpartners', verbose_name='Партнер'),
        ),
    ]
