# Generated by Django 5.0.7 on 2024-08-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_aboutimages_partner'),
    ]

    operations = [

        migrations.AddField(
            model_name='contactinformation',
            name='working_hours_polyclinic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Часы работы поликлиники'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='working_hours_sticionar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Часы работы стационара'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='working_hours_weekdays',
            field=models.CharField(max_length=50, verbose_name='Часы работы'),
        ),
    ]
