# Generated by Django 5.0.7 on 2024-08-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_aboutimages_partner'),
    ]

    operations = [



    ]
