# Generated by Django 5.0.7 on 2024-08-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_contactinformation_working_hours_weekend_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='aboutimages',
        #     name='page',
        # ),
        # migrations.AlterField(
        #     model_name='aboutcard',
        #     name='image',
        #     field=models.FileField(blank=True, null=True, upload_to='about', verbose_name='Изображение'),
        # ),
        # migrations.AlterField(
        #     model_name='aboutfaqimage',
        #     name='image',
        #     field=models.FileField(blank=True, null=True, upload_to='about', verbose_name='Изображение'),
        # ),
        # migrations.AlterField(
        #     model_name='aboutgallery',
        #     name='image',
        #     field=models.FileField(blank=True, null=True, upload_to='about/gallery', verbose_name='Изображение'),
        # ),
        # migrations.AlterField(
        #     model_name='aboutimages',
        #     name='image',
        #     field=models.FileField(blank=True, null=True, upload_to='about-images', verbose_name='Изображение'),
        # ),
        # migrations.AlterField(
        #     model_name='aboutpage',
        #     name='image',
        #     field=models.FileField(blank=True, null=True, upload_to='about', verbose_name='Изображение'),
        # ),
        # migrations.AlterField(
        #     model_name='aboutpartners',
        #     name='image',
        #     field=models.FileField(blank=True, null=True, upload_to='about/partners', verbose_name='Изображение'),
        # ),
    ]
