# Generated by Django 5.0.7 on 2024-08-22 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_aboutimages_page_alter_aboutcard_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Документы', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='documents',
            name='contract_document',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='rules_document',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип документа')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Файл')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pages.documents', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документ',
            },
        ),
    ]
