# Generated by Django 5.0.7 on 2024-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_documents_options_remove_documents_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutgallery',
            name='plaseholder',
            field=models.FileField(blank=True, null=True, upload_to='about/gallery', verbose_name='Плейсхолдер'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_us_image',
            field=models.FileField(blank=True, null=True, upload_to='about', verbose_name='Изображение'),
        ),
    ]
