# Generated by Django 5.0.7 on 2024-08-24 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_aboutimages_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimages',
            options={'verbose_name': 'Изображение партнера', 'verbose_name_plural': 'Изображения партнеров'},
        ),
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),

        migrations.AddField(
            model_name='contactinformation',
            name='working_hours_polyclinic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Часы работы поликлиники'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='working_hours_sticionar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Часы работы стационара'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип документа')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Файл')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pages.documents', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документ',
            },
        ),
    ]
