# Generated by Django 5.0.7 on 2024-08-24 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_aboutimages_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета заголовок')),
                ('meta_description',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета описание')),
                ('meta_image',
                 models.FileField(blank=True, null=True, upload_to='meta_images', verbose_name='Мета изображение')),
                ('keywords', models.TextField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Метаданные',
                'verbose_name_plural': 'Метаданные',
            },
        ),
    ]
