# Generated by Django 5.0.7 on 2024-09-03 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_aboutimages_page_and_more'),
    ]

    operations = [

    ]
