# Generated by Django 5.0.7 on 2024-09-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_aboutimages_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страница')),
                ('image', models.FileField(blank=True, null=True, upload_to='backgrounds/gallery', verbose_name='Задний фон формы')),
            ],
            options={
                'verbose_name': 'Изображение заднего фона',
                'verbose_name_plural': 'Изображения заднего фона',
            },
        ),
    ]
