# Generated by Django 5.0.7 on 2024-09-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_formbackgroundimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbackgroundimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='formbackgroundimage',
            name='slug',
        ),
        migrations.AddField(
            model_name='formbackgroundimage',
            name='about_background',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение заднего фона для "О нас"'),
        ),
        migrations.AddField(
            model_name='formbackgroundimage',
            name='contacts_background',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение заднего фона для "Контакты"'),
        ),
        migrations.AddField(
            model_name='formbackgroundimage',
            name='directions_background',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение заднего фона для "Направления"'),
        ),
        migrations.AddField(
            model_name='formbackgroundimage',
            name='docs_background',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение заднего фона для "Документы"'),
        ),
        migrations.AddField(
            model_name='formbackgroundimage',
            name='doctors_background',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение заднего фона для "Врачи"'),
        ),
        migrations.AddField(
            model_name='formbackgroundimage',
            name='main_background',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение заднего фона для "Главной страницы"'),
        ),
        migrations.AddField(
            model_name='formbackgroundimage',
            name='prices_background',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение заднего фона для "Цены"'),
        ),
    ]
