# Generated by Django 5.0.7 on 2024-09-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_formbackgroundimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('site_description', models.TextField(verbose_name='Описание сайта')),
                ('site_logo', models.FileField(blank=True, null=True, upload_to='site_logos', verbose_name='Логотип сайта')),
                ('site_bottom_logo', models.FileField(blank=True, null=True, upload_to='site_logos', verbose_name='Логотип нижней части сайта')),
                ('site_favicon', models.FileField(blank=True, null=True, upload_to='site_favicons', verbose_name='Иконка сайта')),
                ('telegram_bot_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID бота Telegram')),
                ('telegram_channels', models.TextField(blank=True, null=True, verbose_name='Каналы Telegram')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        )

    ]
