# Generated by Django 5.0.7 on 2024-08-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='doctors', verbose_name='Фото'),
        ),
    ]
