# Generated by Django 5.0.7 on 2024-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='reviews', verbose_name='Фото'),
        ),
    ]
