# Generated by Django 5.0.7 on 2024-08-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_review_patient_name_remove_review_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='сertificate',
            old_name='file',
            new_name='image',
        ),
    ]
