# Generated by Django 5.0.7 on 2024-10-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='docktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='doctors.doctor', verbose_name='Врач'),
        ),
    ]
